#+TITLE: Project Title
#+AUTHOR: Your Name
#+OPTIONS: toc:t num:nil

* Overview
This repository contains the code accompanying the publication:

Title: Widespread Functional Tradeoffs Govern Forest Response to Drought
Authors: Jacob I. Levine and William R. L. Anderegg

The purpose of this codebase is to reproduce the analyses and figures presented in the paper and to provide a transparent, reusable implementation of the methodology.

** Repository Structure
#+BEGIN_SRC text
.
├── data/          # Raw and processed data (see notes below)
├── src/           # Source code and core methods
├── scripts/       # Analysis and figure-generation scripts
├── figures/       # Generated figures
├── tables/        # Results tables
├── manuscript/    # Manuscript files
└── README.org
#+END_SRC

** Requirements

This project was developed and tested with:

	+ Operating system: macOS Sonoma 14.6 on Apple M3 Pro Silicon
	+ Language(s): R 4.4.1, Julia 1.12.1
   + Key dependencies specified in =Project.toml= and =Manifest.toml=

     
* Data Availability
** Input Data

Neither raw nor intermediate data files are provided due to size limitations. However, all the data required to reproduce the analysis are publicly available. Specifically, the following are required: 

+ FIA -- a script for downloading the necessary FIA files is provided =scripts/01_download_fia.r=
+ TRY -- has to be downloaded directly from the [[https://www.try-db.org/TryWeb/Home.php][TRY database]] after making an account ([[https://doi.org/10.1111/j.1365-2486.2011.02451.x]]). A script is provided which generates the list of species codes to download from TRY is provided =scripts/04_pull_trait_data.jl=
+ XFT -- can be downloaded directly from this [[https://xylemfunctionaltraits.org/][link]]
+ TerraClimate -- can be downloaded directly from this [[https://www.climatologylab.org/terraclimate.html][link]]
+ EPA Ecoregions -- Level I and II ecoregion maps are available for download from this [[https://www.epa.gov/eco-research/ecoregions-north-america][link]]
  
All intermediate and output data generated by the scripts will be written to the =data/= and =tables/= directories.

* Reproducibility
To reproduce the main results of the paper:

	1. Set up the environment (see Requirements)
	2. Obtain input data (see Data Availability)
	3. Run the analysis pipeline:
           + step through scripts in =scripts/= in numerical order to download, clean, and merge required datasets
           + step through scripts in =scripts/analysis/= to run statistical analyses and generate figures and output tables
 
