#+title:
#+author:
#+date:

#+options: toc:nil num:nil
#+latex_class: article
#+latex_class_options: [11pt]

#+latex_header: \usepackage{times}
#+latex_header: \usepackage{setspace}
#+latex_header: \usepackage[margin=1in]{geometry}
#+latex_header: \setlength{\parindent}{0pt}
#+latex_header: \setlength{\parskip}{1em}

#+latex_header: \usepackage{fancyhdr}
#+latex_header: \usepackage{graphicx}
#+latex_header: \pagestyle{fancy}
#+latex_header: \fancyhf{}
#+latex_header: \fancyhead[R]{\includegraphics[height=1.5cm]{utah_logo.png}}
#+latex_header: \renewcommand{\headrulewidth}{0pt}

February 4th, 2026

Dear Dr. Thrall,

I am writing to ask that you consider our manuscript titled “Widespread Functional Tradeoffs Govern Forest Response to Drought,” for publication as a letter in /Ecology Letters/. We believe that this paper, which finds that forest communities across the contiguous United States consistently exhibit tradeoffs between drought tolerance and resource acquisitiveness, and that these tradeoffs are associated with increased resilience to drought, represents a novel and exciting contribution to ecology. Moreover, it is one that we as authors with a mix of empirical, theoretical, and ecophysiological backgrounds are uniquely suited to make.

Mortality and productivity loss from drought are among the largest threats to Earth's forests in the 21st century, yet the mechanisms that govern forest response to drought remain poorly resolved. Functional traits, namely those governing species' tolerance to drought and ability to acquire resources like water and carbon, are known to play a key role in the drought resilience of forest communities. Recent theoretical work indicates that these traits, and specifically tradeoffs between drought tolerance and resource acquisitiveness, are also central to the dynamics of competition and coexistence in water-limited plant communities, suggesting a possible link between community assembly and drought responses. However, it is not currently known whether drought tolerance--acquisitiveness tradeoffs are prevalent at the community level, and if so, what their role is in forest response to drought.

In this study we use national-scale forest inventory data linked to comprehensive functional trait databases to investigate: (i) whether tradeoffs between drought tolerance and resource acquisitiveness are prevalent; and (ii) whether communities that more closely adhere to these tradeoffs are more resilient to drought impacts on growth and mortality. Our analysis shows that community-level drought tolerance–acquisitiveness tradeoffs are widespread across U.S. forests and are often stronger than would be expected from physiological constraints alone, consistent with predictions from resource-competition theory. Importantly, we find that communities that more closely adhere to these tradeoffs (i.e., show tighter alignment of species to the tradeoff curve) experience lower mortality and higher basal-area growth during drought. These results implicate community assembly and functional tradeoffs as key determinants of drought resilience and suggest that the earth system models currently used to predict future vegetation may miss important dynamics by omitting the mechanisms that maintain biodiversity in nature.

We believe this work is worthy of publication in /Ecology Letters/ due to its synthesis of ecophysiology, community ecology, and ecosystem dynamics, and linking of recent theoretical advances with large-scale empirical patterns. Such a synthesis lays a path forward for understanding the relationship between community ecology, ecosystem function, and global change that will appeal to the broad readership of the journal. 

Sincerely,

@@latex:\noindent\includegraphics[height=1.5cm]{signature.png}@@

*Jacob Levine* \newline
Wilkes Center for Climate Science and Policy \newline
University of Utah \newline
Salt Lake City, UT \newline
jacob.levine@utah.edu \newline
